# Generated by Django 4.1.7 on 2023-03-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='razor_pay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='razor_pay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='razor_pay_payment_signature',
            new_name='razorpay_payment_signature',
        ),
    ]
