# Generated by Django 4.1.7 on 2023-04-04 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cart_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_id',
        ),
    ]
